version: '3.7'

services:
  db:
    container_name: howtocards_db
    image: postgres
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=howtocards
      - POSTGRES_PASSWORD=howtocards
      - POSTGRES_DB=howtocards
    ports:
      - 5432:5432

  backend:
    container_name: howtocards_backend
    build:
      context: .
      dockerfile: Dockerfile
    image: howtocards/backend
    restart: always
    volumes:
      - ./migrations:/app/migrations
      - ./diesel.toml:/app/diesel.toml
    ports:
      - 9000:9000
    links:
      - db
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://howtocards:howtocards@db/howtocards
