version: '3.7'

services:
  db:
    container_name: howtocards_db
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432

  backend:
    container_name: howtocards_backend
    build:
      context: .
      dockerfile: Dockerfile
    image: howtocards/backend
    restart: always
    volumes:
      - ./migrations:/app/migrations
      - ./diesel.toml:/app/diesel.toml
    ports:
      - 9000:9000
    links:
      - db
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
